environment:
  CTEST_OUTPUT_ON_FAILURE: 1
  matrix:
    - BUILD: mingw

install:
  - choco install -y mingw
  - choco install -r -y ninja
  - choco install -y winflexbison
  - "SET PATH=C:\\tools\\mingw64\\bin;%PATH%"

build_script:
  - git submodule init
  - git submodule update
  - mkdir build
  - cd build
  - cmake -G Ninja ..
  - ninja
