environment:
  CTEST_OUTPUT_ON_FAILURE: 1
  matrix:
    - BUILD: mingw

install:
  - choco install -y mingw
  - choco install -r -y ninja
  - choco install -y winflexbison
  - choco install -y swig
  - "SET PATH=C:\\tools\\mingw64\\bin;%PATH%"
  - bash -lc "pacman -Sy mingw-w64-i686-boost mingw-w64-x86_64-boost"

build_script:
  - git submodule init
  - git submodule update
  - mkdir build
  - cd build
  - cmake -G Ninja ..
  - ninja
